### ISSUE TITLE
Board

### ISSUE THREAD

**Issue by Aki-7** [zwin-project/zen#111]
### Specification
 
- [ ] create the concept of board #109 
  - A screen has many boards
  - A screen must have at least one board
  - A board must be owned by one screen if there are some screen.
  - If there is no screen, boards can be owned by no screen. (**dangling board**)
  - A boards has many views
  - A mapped view must be owned by one board.
  - A screen must have current board, which is shown to a display.
- [ ] handle screen creation/destruction #109 
  - When a screen is created
    - if there is no dangling board (another screen exists), create a new board and assign it to the screen.
    - if there is dangling board, assign one of the dangling board to the screen.
  - When a screen is destroyed
    - if there are screens remaining, assign destroyed screen's boards to the remaining screen.
    - if there is no screen remaining, the boards will be dangling boards. 
- [ ] move between boards #109 
  - `<mod> + <shift> + →`: move to the next board on the screen which cursor is on.  
  - `<mod> + <shift> + ←`: move to the previous board on the screen which cursor is on.  
- [ ] enable to create new board #109 
- [ ] enable to destroy board
- [ ] enable to move board between screens
- [ ] enable to move view between boards
- [ ] draw the appearance of boards.

#### Dangling board

A Board which is not assigned to any screen. Dangling board can exist only when there is no screen (no output connected).
