### ISSUE TITLE
Switching display system

### ISSUE THREAD

**Issue by Aki-7** [zwin-project/zen#78]
Enable switching between "immersive display system" used when working in XR and "screen display system" used when working on a physical monitor.
The details of what is rendered on each display system are not the scope of this issue, but running the rendering and event loop on the immersive display system is within the scope of this issue.

# Milestone
- [x] write a protocol to switch display systems. #73 
- [x] create a client which implement the protocol. #76 
- [x] create `openvr` backend as the first option of "immersive backend", and check if immersive display system is now available or not when a client request server to switch display system to "immersive". #84 
- [ ] run openvr rendering and event loop together with wayland event loop.
  - [ ] without any actual rendering #92
  - [ ] render some object, e.g. floor
